title: My Digital Products
url: "https://example.github.io"
baseurl: "/my-digital-products"

collections:
  products:
    output: true
    permalink: /products/:slug

defaults:
  - scope:
      path: ""
      type: "products"
    values:
      layout: "product"

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-compress-html

compress_html:
  clippings: all
  comments: ["<!-- Comments to ignore -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: true
  profile: false
  startings: [html, head, body]

sass:
  style: compressed
