title: My Digital Products
url: "https://produkdigital101.netlify.app"
baseurl: ""

collections:
  products:
    output: true
    permalink: /products/:slug

defaults:
  - scope:
      path: ""
      type: "products"
    values:
      layout: "product"

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-compress-html

sass:
  style: compressed
