- name: Product 1
  description: Deskripsi singkat produk 1
  cover_image: /assets/images/product1-cover.jpg
  gallery_images:
    - /assets/images/product1-image1.jpg
    - /assets/images/product1-image2.jpg
    # ... max 10 images
  details: >
    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    Fusce at augue ac nisl tincidunt fermentum...

- name: Product 2
  description: Deskripsi singkat produk 2
  cover_image: /assets/images/product2-cover.jpg
  gallery_images:
    - /assets/images/product2-image1.jpg
    - /assets/images/product2-image2.jpg
    # ... max 10 images
  details: >
    Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium...
